FROM python:3.7

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends dos2unix
RUN apt-get install -y curl
COPY data_handler/sqlite_to_mysql.py ./data_handler/sqlite_to_mysql.py
COPY data/market.db ./data/market.db
RUN dos2unix ./data_handler/sqlite_to_mysql.py

RUN python -m pip install -U setuptools wheel
COPY requirements.txt ./requirements.txt
RUN python -m pip install -r requirements.txt
WORKDIR ./data_handler
CMD ["python", "sqlite_to_mysql.py"]